### PR TITLE
Removed peclib.

### PR DESCRIPTION
**Pull request by TotallyNotVirtIO**
Change the links in the files to point to your repo btw.

### CODE REVIEW

**Review by Apethesis — CHANGES_REQUESTED** [review]
Update to latest commit and fix the links please, thanks.

**Comment by TotallyNotVirtIO** [comment]
Skill issue

**Comment by TotallyNotVirtIO** [comment]
Now merge

**Comment by TotallyNotVirtIO** [comment]
@Apethesis merge you skill issue

**Comment by TotallyNotVirtIO** [comment]
oh so updater is broken
ima fix it real quick

**Comment by Apethesis** [comment]
i dunno man 
it seems like a bad idea to merge

**Comment by TotallyNotVirtIO** [comment]
why

**Comment by TotallyNotVirtIO** [comment]
you literally said that you'll accept the damn pr

**Comment by TotallyNotVirtIO** [comment]
yes the commits are unsigned but git is just retarded and forgot to use my gpg key

**Comment by TotallyNotVirtIO** [comment]
@Apethesis

**Comment by TotallyNotVirtIO** [comment]
merge

**Comment by TotallyNotVirtIO** [comment]
***now***

**Comment by Apethesis** [comment]
you need signed commits
sorry

**Comment by TotallyNotVirtIO** [comment]
bruh

**Comment by TotallyNotVirtIO** [comment]
FUCKS SAKE

**Comment by Apethesis** [comment]
you ok bud?

**Comment by TotallyNotVirtIO** [comment]
no

**Comment by TotallyNotVirtIO** [comment]
git is retarded

**Comment by Apethesis** [comment]
noob

**Comment by Apethesis** [comment]
nah the original commits have to be signed aswell
sorry

**Comment by TotallyNotVirtIO** [comment]
i literally cant sign them anymore

**Comment by Apethesis** [comment]
too bad

**Comment by Apethesis** [comment]
ah fuck wrong button

**Pull request merged**
