### PR TITLE
Revert "Removed peclib."

### PR DESCRIPTION
**Pull request by Apethesis**
Reverts Apethesis/CC-Code#12

### CODE REVIEW

**Comment by Apethesis** [comment]
@TotallyNotVirtIO

**Comment by TotallyNotVirtIO** [comment]
bruh you asshole

**Comment by TotallyNotVirtIO** [comment]
fuckin

**Comment by TotallyNotVirtIO** [comment]
merge it again

**Comment by TotallyNotVirtIO** [comment]
revert the fucking revert

**Comment by TotallyNotVirtIO** [comment]
i spent way too long fixing your shit

**Comment by TotallyNotVirtIO** [comment]
@Apethesis

**Comment by TotallyNotVirtIO** [comment]
i literally offer you free labor and you refuse

**Comment by SkyTheCodeMaster** [comment]
This PR appears to worsen the functionality of many programs in this repository.
👎 from me

**Comment by TotallyNotVirtIO** [comment]
sky you asshole

**Comment by TotallyNotVirtIO** [comment]
wait no im dumb

**Comment by TotallyNotVirtIO** [comment]
or wait are you talking about the revert or my pr

**Comment by Apethesis** [comment]
> This PR appears to worsen the functionality of many programs in this repository. 👎 from me

the pr makes them better trust me

**Pull request merged**
