### PR TITLE
Remove peclib but i fixed the errors.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Apethesis** [comment]
image
mmmmh
naaah

**Comment by TotallyNotVirtIO** [comment]
the fuck do you mean

**Comment by Apethesis** [comment]
naaah

**Comment by TotallyNotVirtIO** [comment]
what if i improve peclib

**Comment by TotallyNotVirtIO** [comment]
bruh compec

**Comment by TotallyNotVirtIO** [comment]
you asshole

**Comment by TotallyNotVirtIO** [comment]
> > what if i improve peclib
> 
> wdym improve its already decent enough for me

not good enough for me

**Comment by TotallyNotVirtIO** [comment]
im gonna improve it

**Comment by Apethesis** [comment]
explain how your gonna "improve" it

**Comment by TotallyNotVirtIO** [comment]
not have it be spaghetti

**Comment by TotallyNotVirtIO** [comment]
maybe add something you want lmao

**Comment by TotallyNotVirtIO** [comment]
it is

**Comment by TotallyNotVirtIO** [comment]
your or chain

**Comment by Apethesis** [comment]
> maybe add something you want lmao

i dont want anything more to peclib
i like it how it currently is

**Comment by Apethesis** [comment]
"comlib" compec's library

**Comment by TotallyNotVirtIO** [comment]
still

**Comment by TotallyNotVirtIO** [comment]
https://github.com/TotallyNotVirtIO/Rewriting-compecs-programs-without-peclib/tree/main
@Apethesis

**Comment by Apethesis** [comment]
what

**Comment by TotallyNotVirtIO** [comment]
what do you not understand

**Comment by TotallyNotVirtIO** [comment]
@Apethesis make an issue if you want lmao

**Pull request closed without merging**
